### ISSUE TITLE
Error: EACCES: permission denied.

### ISSUE THREAD

**Issue by Sakamoto0525** [Sakamoto0525/todoapp-for-nestjs#1]
# エラー

docker compose run時にエラー

```bash
npm ERR!  Error: EACCES: permission denied, mkdir '/home/sakamoto/projects/private/todoapp/node_modules/@aashutoshrathi'
npm ERR!     at async mkdir (node:internal/fs/promises:859:10)
npm ERR!     at async /home/sakamoto/.asdf/installs/nodejs/21.7.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:546:20
npm ERR!     at async Promise.allSettled (index 0)
npm ERR!     at async [reifyPackages] (/home/sakamoto/.asdf/installs/nodejs/21.7.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:246:11)
npm ERR!     at async Arborist.reify (/home/sakamoto/.asdf/installs/nodejs/21.7.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:165:5)
npm ERR!     at async Install.exec (/home/sakamoto/.asdf/installs/nodejs/21.7.2/lib/node_modules/npm/lib/commands/install.js:153:5)
npm ERR!     at async module.exports (/home/sakamoto/.asdf/installs/nodejs/21.7.2/lib/node_modules/npm/lib/cli-entry.js:61:5) {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/sakamoto/projects/private/todoapp/node_modules/@aashutoshrathi'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /home/sakamoto/.npm/_logs/2024-04-22T11_36_59_091Z-debug-0.log
```

```bash
todoapp-backend-1  | src/main.ts:2:48 - error TS2307: Cannot find module '@nestjs/swagger' or its corresponding type declarations.
todoapp-backend-1  | 
todoapp-backend-1  | 2 import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
todoapp-backend-1  |                                                  ~~~~~~~~~~~~~~~~~
todoapp-backend-1  | 
todoapp-backend-1  | [11:32:52 AM] Found 1 error. Watching for file changes.
todoapp-backend-1  | 
```

# 原因

Docker内からnode_modulesに対してのアクセス権限がない
そのせいでnpm i @nestjs/swaggerがinstallできない

**Comment by Sakamoto0525** [comment]
解決したのでClose

最初DockerfileでUser nodeとDockerfileで書かれている処理を実行するユーザーをnodeに固定していた
それを一旦コメントアウトし、npm iはローカル（コンテナではない）で実行

> ただ、このエラーの対処法としてUser nodeと指定するのが手とある記事でみたので、なぜこのエラーが発生したのかは謎

**Comment by Sakamoto0525** [comment]
# 参考記事

- [npm コマンドのローカル/グローバル実行が “EACCES: permission denied”となる場合の対処](https://dev.classmethod.jp/articles/handling-eacces-permission-denied-for-npm-commands/)
  - chownでディレクトリに対するアクセス権をユーザーに付与する対応がわかった。
- [Node.js on Dockerでエラー発生(Error: EACCES: permission denied, errno: -13)](https://qiita.com/bachikawa/items/b88fc68d874b787a541e)
  - DockerFileにUSERの指定を追記したら解決するらしい。という情報をGET
- [Next.js on Docker で npm install すると permission denied が出る](https://zenn.dev/ndjndj/scraps/9357a21f81dff4)
  - node_modules を削除→npm install してみるという部分を見て、一旦消して期待するユーザーで作成することで、そのユーザーが所有権を持った状態でディレクトリをつくればいいか、、という結論に至った

**Comment by Sakamoto0525** [comment]
# 権限関連のチートシート

```bash
# 権限確認
ls -l .

# ユーザー作成
useradd -m myuser

# ユーザー作成 (UID, GID指定)
useradd -m -u 101 -g 1001 myuser

# ユーザーをグループに追加
usermod -aG groupname myuser

# ユーザーのパスワードを設定
echo 'myuser:mypassword' | chpasswd

# ユーザー削除
userdel myuser

# ユーザー切り替え
USER myuser

# 作業ディレクトリの所有者を変更する
chown -R myuser:myuser /path/to/directory

# 特権モード
USER root
```
